# Release automation (Rust)
#
# Purpose:
# - When Cargo.toml changes on master, build/test and then tag the version
# - If the tag is new, merge master back into develop
on:
  push:
    branches:
      - master
    paths:
      - 'Cargo.toml'

# Shared environment settings.
env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable

# Job: build
# - Build and test the project before releasing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ env.TOOLCHAIN }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  # Job: release
  # - Read version from Cargo.toml
  # - Create tag if missing
  # - Merge master into develop after tagging
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-get
        run: cargo install cargo-get

      - name: Extract version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(cargo get package.version)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Version: v$VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "⚠️  Tag ${{ steps.get_version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "✅ Tag ${{ steps.get_version.outputs.version }} will be created"
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}
          echo "✅ Tag ${{ steps.get_version.outputs.version }} created and pushed"

      - name: Merge master into develop
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin develop
          git checkout develop
          git merge origin/master --no-ff -m "Merge master into develop after release ${{ steps.get_version.outputs.version }}"
          git push origin develop
          echo "✅ Master merged into develop"
