# Validation (Rust)
#
# Purpose:
# - Run formatting, linting, build, tests, and coverage for Rust projects
# - Provide non-blocking feedback for formatting, linting, and coverage
name: Validation (Rust)

# Run on pushes to develop and PRs to master.
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

# Shared environment settings.
env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable
  TARPAULIN_VERSION: 0.34.1

# Job: build
# - Checkout
# - Install toolchain + components and cache
# - rustfmt and Clippy (non-blocking)
# - Build and test
# - Coverage and Codecov upload (non-blocking)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ env.TOOLCHAIN }}
        components: |
          clippy
          rustfmt
        cache: true        # enable automatic caching (default, but explicit)
        cache-bin: true    # ensure ~/.cargo/bin (tarpaulin etc.) is cached
        rustflags: ""      # avoid forcing RUSTFLAGS="-D warnings"

    - name: Detect library crate (cargo metadata)
      id: crate_kind
      run: |
        python3 - <<'PY'
        import json, os, subprocess
        data = json.loads(subprocess.check_output(["cargo", "metadata", "--no-deps", "--format-version=1"]))
        has_lib = any("lib" in (t.get("kind") or []) for p in data.get("packages", []) for t in p.get("targets", []))
        with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as f:
          f.write(f"has_lib={'true' if has_lib else 'false'}\n")
        print("has_lib =", has_lib)
        PY

    - name: Check code formatting
      uses: actions-rust-lang/rustfmt@v1
      continue-on-error: true

    - name: Lint with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      continue-on-error: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Generate code coverage
      if: steps.crate_kind.outputs.has_lib == 'true'
      run: |
        cargo install cargo-tarpaulin --version ${{ env.TARPAULIN_VERSION }} --locked || cargo tarpaulin --version
        cargo tarpaulin --out Xml
      continue-on-error: true

    - name: Upload coverage to Codecov
      if: steps.crate_kind.outputs.has_lib == 'true'
      uses: codecov/codecov-action@v5
      with:
        files: tarpaulin-report.xml
        fail_ci_if_error: false
